language: objective-c
osx_image: xcode11.3
script:
  - xcodebuild test -project FlexBuffers.xcodeproj -scheme FlexBuffers ONLY_ACTIVE_ARCH=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)
